version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
          name: Running app tests
          command: |
            python -m unittest -v test.py
      - heroku/deploy-via-git

workflows:
  heroku_deploy:
    jobs:
      - deploy
