version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6

workflows:
    deploy-parser:
      jobs:
        - run: echo "Deploying PDF Parser"
        - heroku/deploy-via-git:
            force: true
            maintenance-mode: false